import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Navbar from './Navbar';
import { relative } from 'path';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang='en'>
			<body
				className={inter.className}
				style={{
					width: '100%',
					height: '100%',
					overflow: 'hidden',
					// position: 'relative',
				}}
			>
				<Navbar />
				<div className='absolute w-full flex justify-center mt-20 ml-4 overflow-y-scroll box-content top-0 bottom-0 left-0 -right-5'>
					{children}
				</div>
			</body>
		</html>
	);
}
